import * as XLSX from "xlsx";

const memberHeaders = [
  "householdCode",
  "householdHeadName",
  "householdPhone",
  "zoneCode",
  "zoneName",
  "arrivalDate",
  "memberIndex",
  "memberName",
  "firstName",
  "lastName",
  "fatherName",
  "motherName",
  "civilIdentityNumber",
  "phoneNumber",
  "originArea",
  "nationality",
  "gender",
  "age",
  "relationshipToHead",
  "yearOfBirth",
  "idDocStatus",
  "idDocType",
  "idDocLast4",
  "schoolEnrollment",
  "employmentStatus",
  "memberSafetyCheckStatus",
  "hasDisability",
  "hasChronicCondition",
  "pregnantOrLactating",
  "hasCar",
  "carModel",
  "carColor",
  "carPlate",
  "householdLat",
  "householdLng",
  "googleMapsLink",
  "mapImageUrl"
] as const;

const exampleRows: Array<Array<string | number | boolean>> = [
  [
    "HH-00001",
    "Christian Gemayel",
    "70119922",
    "S1",
    "Section 1",
    "2026-03-06",
    1,
    "Christian Gemayel",
    "Christian",
    "Gemayel",
    "Youssef",
    "Magui",
    "123456",
    "70119922",
    "Bickfaya",
    "Lebanese",
    "MALE",
    26,
    "HEAD",
    2000,
    "HAS_ID",
    "NATIONAL_ID",
    "3456",
    "NA",
    "EMPLOYED",
    "CHECKED_SAFE",
    false,
    false,
    false,
    true,
    "Toyota",
    "White",
    "123456",
    33.936665,
    35.699494,
    "https://www.google.com/maps?q=33.936665,35.699494",
    ""
  ],
  [
    "HH-00001",
    "Christian Gemayel",
    "70119922",
    "S1",
    "Section 1",
    "2026-03-06",
    2,
    "Maria Gemayel",
    "Maria",
    "Gemayel",
    "Youssef",
    "Magui",
    "",
    "",
    "Bickfaya",
    "Lebanese",
    "FEMALE",
    21,
    "DAUGHTER",
    2005,
    "NO_ID",
    "",
    "",
    "ENROLLED",
    "NA",
    "PENDING",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    33.936665,
    35.699494,
    "",
    ""
  ]
];

const instructionsRows: Array<Array<string>> = [
  ["Rule", "Details"],
  ["Do not rename this sheet", "Keep the members sheet name exactly: All Members"],
  ["One row per member", "Families with multiple members must have multiple rows"],
  ["Duplicate behavior", "Existing families are matched by householdCode first, then head+phone+arrivalDate"],
  ["Date format", "Use YYYY-MM-DD (example: 2026-03-06)"],
  ["Gender values", "MALE or FEMALE"],
  ["ID status values", "HAS_ID, NO_ID, or UNKNOWN"],
  ["School values", "ENROLLED, NOT_ENROLLED, or NA"],
  ["Employment values", "EMPLOYED, UNEMPLOYED, or NA"],
  ["Safety status values", "CHECKED_SAFE or PENDING"],
  ["Boolean values", "Use TRUE/FALSE or 1/0 for yes/no fields"],
  ["Coordinates", "householdLat/householdLng are optional; googleMapsLink can also be used"],
  ["Optional fields", "Missing optional values are allowed and can be edited later in the website"]
];

export function buildHouseholdImportTemplateWorkbook() {
  const workbook = XLSX.utils.book_new();
  const membersSheet = XLSX.utils.aoa_to_sheet([Array.from(memberHeaders), ...exampleRows]);
  const instructionsSheet = XLSX.utils.aoa_to_sheet(instructionsRows);
  XLSX.utils.book_append_sheet(workbook, membersSheet, "All Members");
  XLSX.utils.book_append_sheet(workbook, instructionsSheet, "Instructions");
  return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });
}
